FROM python:3.12-slim
WORKDIR /app
COPY pyproject.toml README.md ./
COPY src ./src
RUN pip install --no-cache-dir '.[postgres]'
ENV PYTHONUNBUFFERED=1 AI_LOGGER_SERVER_HOST=0.0.0.0 AI_LOGGER_SERVER_PORT=8766 AI_LOGGER_REQUIRE_POSTGRES=1 AI_LOGGER_SERVER_PROJECT_DAILY_DIR=/app/logs AI_LOGGER_WEB_LOGS_ROOT=/app/logs
EXPOSE 8766
CMD ["ai-logger-server"]
